name: weixin
on:
  workflow_dispatch:
  schedule: 
    # 代表国际标准时间23点0分，北京时间需要+8小时，代表北京时间上午7点运行
    - cron: '0 23 * * *'
jobs:
#将工作流程中运行的所有作业组合在一起
  build:
  #定义名为 build 的作业。 子键将定义作业的属性 
    runs-on: ubuntu-20.04 
    steps:
      - uses: actions/checkout@v2
    
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9.1
      -名称：设置时区
        运行：|
          cp /usr/share/zoneinfo/Asia/上海 /etc/localtime
      -名称：安装pip包
        运行：|
          python -m pip install --升级 pip
          pip3 install -r 要求.txt
      -姓名：微信
        运行：|
          python3 main.py
